### PR TITLE
[minor] Updated alpine to 3.19.1

### PR DESCRIPTION
**Pull request by nigelgbanks**
- Custom nodejs package to support code-server.
- Update imagemagick / leptonica.
- PHP/FPM 8.3

### CODE REVIEW

**Comment by alxp** [comment]
I tried to build this using the latest 'development' branch of ISLE-DC and it started printing out this waiting message until it failed, this happened twice after clean builds on macOS Sonoma 14.4.1.

```bash
al.php
  - Copy [web-root]/sites/example.sites.php from assets/scaffold/files/example.sites.php
  - Copy [web-root]/sites/default/default.services.yml from assets/scaffold/files/default.services.yml
  - Copy [web-root]/sites/default/default.settings.php from assets/scaffold/files/default.settings.php
  - Copy [web-root]/modules/README.txt from assets/scaffold/files/modules.README.txt
  - Copy [web-root]/profiles/README.txt from assets/scaffold/files/profiles.README.txt
  - Copy [web-root]/themes/README.txt from assets/scaffold/files/themes.README.txt
Scaffolding files for islandora/islandora-starter-site:
  - NOTICE Creating a new file at [web-root]/sites/default/settings.php. Examine the contents and ensure that it came out correctly.
  - Append to [web-root]/sites/default/settings.php from assets/patches/default_settings.txt
/Library/Developer/CommandLineTools/usr/bin/make starter-finalize ENVIRONMENT=starter_dev
docker compose exec -T drupal with-contenv bash -lc 'chown -R nginx:nginx . ; echo "Chown Complete"'
Chown Complete
/Library/Developer/CommandLineTools/usr/bin/make drupal-database update-settings-php
Waiting for nginx and php-fpm
Waiting for nginx and php-fpm
Waiting for nginx and php-fpm
Waiting for nginx and php-fpm
Waiting for nginx and php-fpm
Waiting for nginx and php-fpm
Waiting for nginx and php-fpm
Waiting for nginx and php-fpm
Waiting for nginx and php-fpm
Waiting for nginx and php-fpm
Waiting for nginx and php-fpm
```

**Comment by aOelschlager** [comment]
@alxp I'm sorry, I forgot about that part in isle-dc. This line would need to change for php 8.3: https://github.com/Islandora-Devops/isle-dc/blob/development/Makefile#L117

**Comment by alxp** [comment]
OK I'll try and run the build again will likely happen after work today.

**Comment by alxp** [comment]
I just tested the ISLE-DC build after fixing the PHP version and it builds and I get the Drupal site.

**Comment by aOelschlager** [comment]
Thank you @nigelgbanks and @alxp!

**Pull request merged**
