### PR TITLE
Add support for postgres where possible, and now support database bot…

### PR DESCRIPTION
**Pull request by nigelgbanks**
…h database for fcrepo.

This is significantly bigger pull as I've refactored as much of the database logic down into the base image so it can be shared by all the services.

This required changing the defaults from 'database' to the specific implementation since 'matomo' does not work with postgresql we can't assume only one database in the stack (if users choose to use postgres) so the defaults have changed to 'mariadb'.

To be tested along with https://github.com/Islandora-Devops/isle-dc/pull/86

### CODE REVIEW

**Comment by nigelgbanks** [comment]
Address https://github.com/Islandora-Devops/isle-buildkit/issues/9

**Comment by dannylamb** [comment]
@nigelgbanks Can you resolve the conflicts on this?  Normally I'd do it myself but Github's not letting me through the UI.

**Comment by nigelgbanks** [comment]
@dannylamb will do

**Comment by nigelgbanks** [comment]
@dannylamb ready to go

**Comment by dannylamb** [comment]
Testing now :rocket:

**Pull request merged**
