### PR TITLE
Adding toggle for installing islandora_defaults instead of trying to …

### PR DESCRIPTION
**Pull request by dannylamb**
…detect it

Test with https://github.com/Islandora-Devops/isle-dc/pull/159, which lets you set `ENABLE_ISLANDORA_DEFAULTS` in your .env to toggle this behaviour.

### CODE REVIEW

**Review by nigelgbanks — CHANGES_REQUESTED** [review]
Other than the `local` issue it looks safe to be merged.

**Comment by DonRichards** [comment]
So, is it going to get merged?

**Comment by nigelgbanks** [comment]
The `local` issues needs to be fixed first.

**Comment by g7morris** [comment]
Hi @nigelgbanks & @dannylamb curious what action or review is further required here? Should this go into the [March / April 2022 - isle-buildkit 1.0.0 release](https://github.com/Islandora-Devops/isle-buildkit/projects/2) ?

**Comment by nigelgbanks** [comment]
On reviewing this again, I think this should probably just be closed. The function `configure_islandora_default_module` configures solr oddly enough.
https://github.com/Islandora-Devops/isle-buildkit/blob/1484451679b75486b05f48df9614a03887f3f6c6/drupal/rootfs/etc/islandora/utilities.sh#L389-L390

Additionally the added variable `DRUPAL_ENABLE_ISLANDORA_DEFAULTS` should be site specific, like the others prefixed with `DRUPAL_DEFAULT_`.

**Pull request closed without merging**
