### PR TITLE
Matomo upgrade 4142

### PR DESCRIPTION
**Pull request by nigelgbanks**
Rebased to cleanup commit history from pull https://github.com/Islandora-Devops/isle-buildkit/pull/277 also made the source branch on this repository so github actions runs.

### CODE REVIEW

**Comment by nigelgbanks** [comment]
Sorry, travel got delayed, so I took another day to look at this. I reworked download.sh so it worked for the IP database, but in checking the Matomo docs and UI, it seems like the download of the database is an automatically managed feature. So, we don't need to download the database manually. Also, since it's tied to the month, we probably shouldn't bake this into the image directly, as it will rapidly go out of date?

https://matomo.org/faq/how-to/faq_163/

Note: The latest version of Matomo includes an auto-updater for these databases.

**Comment by nigelgbanks** [comment]
@g7morris can you look into https://github.com/Islandora-Devops/isle-buildkit/pull/278#issuecomment-1560257747 and explain why it's required to manually download the database?

**Comment by g7morris** [comment]
Hi @nigelgbanks 

Quick followup. Reviewed further and didn't like the hardcoded elements for the geoIP db which would require constant human intervention and updates. Refactored the code to download and update on every build. I think this would be nicer to do if we agree to bake into the image. 

Additionally this would negate any further need for a bind mount of that file. (ignore my comment on that particular bind mount above if we agreed)

I think we're ready to move forward now.

**Review by g7morris — CHANGES_REQUESTED** [review]
Hi @nigelgbanks 

I've reviewed and updated as requested. 

Over to you again for review.

**Comment by nigelgbanks** [comment]
Hi @g7morris I'll take a crack at this on Thursday. I should have sometime then. Or if I'm not too exhausted at the airport this morning.

**Comment by g7morris** [comment]
I've now updated this to https://github.com/Islandora-Devops/isle-buildkit/tree/matomo-upgrade-4151

**Pull request closed without merging**
