### PR TITLE
Simplify scripts and ensure multi-sites work as well as install from e…

### PR DESCRIPTION
**Pull request by nigelgbanks**
Allows new sites to install from existing configuration (if using minimal or profile with no install hooks).

The hope is that this will be more extensible for images that descend from `islandora/drupal`.

Largely the functionality is the same but the implementation requires less mucking around in confd templates and more bash. Reuseable scripts are available for use such as `create-drupal-database.sh` and  `install-drupal-site.sh`  which decendent images can call directly if they want to override `04-drupal-setup.sh` with custom logic.

The template file `drupal-setup-environment.sh.tmpl` is used to import the confd settings regardless of backend into the scripts environment with the help of `#!/usr/bin/with-contenv bash`. This allows the setting of default values for the environment variables if none is specified but allow confd's backend to be the ultimate decider of the value.

@g7morris hopefully this pattern address the concerns you raised at the last meeting. Let me know your thoughts.

One thing I couldn't work into this pull request is the moving of the volume `drupal-sites-data:/var/www/drupal/web/sites` to instead be `drupal-sites-data:/var/www/drupal/web/sites/default/files` as `settings.php` needs to be regenerated with appropriate values for the database backend, etc. The various composer projects have different behaviour for what they place in `settings.php` also down stream images like `drupal/sandbox` and others may wish to change behaviour. So there does not seem to be a generic way to do it without stepping on peoples toes. 

In my downstream project I've opted to use `drupal/recommended-project` rather than <https://github.com/Islandora/drupal-project> as I need multisite support. So my downstream image is responsible for regenerating `settings.php` for each subsite.

### CODE REVIEW

**Comment by dannylamb** [comment]
Spinning up now to test :rocket:

**Comment by nigelgbanks** [comment]
@dannylamb I just added the extra variable for skipping the install as well DRUPAL_DEFAULT_INSTALL. https://github.com/Islandora-Devops/isle-buildkit/pull/52/commits/fe897c1cbc6c9cee1d9d89262d0a380adeae569a

**Comment by dannylamb** [comment]
Excellent.  The site I'm doing is installing now, but I'll def test that out with what I've ripped from future.islandora.ca

**Comment by dannylamb** [comment]
This is hanging for me.  I'm getting

```
/var/www/drupal # daniel@daniel-Latitude-3560:~/Code/Environments/isle-buildkit$ docker logs -tf isle-buildkit_drupal_1
2020-06-22T18:27:42.536938451Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2020-06-22T18:27:42.923963053Z [s6-init] ensuring user provided files have correct perms...exited 0.
2020-06-22T18:27:42.928356107Z [fix-attrs.d] applying ownership & permissions fixes...
2020-06-22T18:27:42.938642842Z [fix-attrs.d] done.
2020-06-22T18:27:42.951312164Z [cont-init.d] executing container initialization scripts...
2020-06-22T18:27:42.959590943Z [cont-init.d] 01-confd-render-templates.sh: executing... 
2020-06-22T18:27:42.967084039Z Looking for etcd server... http://etcd:2379
2020-06-22T18:27:42.989946110Z Found etcd server...
2020-06-22T18:27:43.237318937Z [cont-init.d] 01-confd-render-templates.sh: exited 0.
2020-06-22T18:27:43.238706631Z [cont-init.d] 02-fpm-install.sh: executing... 
2020-06-22T18:27:43.271187509Z [cont-init.d] 02-fpm-install.sh: exited 0.
2020-06-22T18:27:43.276341939Z [cont-init.d] 02-ngnix-install.sh: executing... 
2020-06-22T18:27:43.305178697Z [cont-init.d] 02-ngnix-install.sh: exited 0.
2020-06-22T18:27:43.307059147Z [cont-init.d] 03-drupal-setup-environment.sh: executing... 
2020-06-22T18:27:43.384394080Z [cont-init.d] 03-drupal-setup-environment.sh: exited 0.
2020-06-22T18:27:43.387696161Z [cont-init.d] 04-drupal-setup.sh: executing... 
2020-06-22T18:27:43.431480252Z Waiting for connection to database.
2020-06-22T18:27:43.442690629Z Waiting for up to 300 seconds to connect to Database database:3306
2020-06-22T18:27:43.453034612Z Waiting for 3306 on database to open.
2020-06-22T18:27:43.465579611Z Database found
2020-06-22T18:27:43.465782440Z Validating Database credentials for root
2020-06-22T18:27:43.487534112Z mysqld is alive
2020-06-22T18:27:43.488844703Z Credentials are valid
2020-06-22T18:27:43.492240769Z Create database 'drupal_default' and users if they do not exist.
2020-06-22T18:27:43.636537241Z Installing site.
```

It just sits there forever and nignx never starts listening.

**Comment by nigelgbanks** [comment]
Hmm I can't reproduce it I wiped my repo (`git clean -xfd .` and system `docker system prune` and was able to build it. In looking where it stopped for you my guess is this is the culprit: ``chown -R nginx:nginx .`` Since there is a bind mount there it might be super slow for lots of small files on OSX. I'll get rid of it some how.

**Comment by dannylamb** [comment]
@nigelgbanks Are you testing using `isle-dc`?  I was still using the docker-compose file in ths repo.   Maybe that's the issue?

**Comment by dannylamb** [comment]
Ah... I had the foresight to let it run for a while.  You're right... it's just craaaaaaaaaaazy slow.  I've moved on, but it took me a couple of hours :disappointed:

**Comment by dannylamb** [comment]
Also, I'm on Ubuntu.  I know file stuff has always been a problem on OSX.  I don't know if that helps or just muddies the water.

**Comment by nigelgbanks** [comment]
Oh it definitely shouldn't take that long on Ubuntu form me its like 10-15 seconds before it gets past the chown

**Comment by nigelgbanks** [comment]
I was also using the docker-compose in the isle-buildkit repo for testing.

**Pull request merged**
