### PR TITLE
Issue 174 - Logging

### PR DESCRIPTION
**Pull request by nigelgbanks**
For [Issue-174](https://github.com/Islandora-Devops/isle-buildkit/issues/174) this removes the use of symlinks and instead appropriately configures the logging for each service using the recommend methods according to their documentation. 

There is one notable exception `handle` still uses symlinks to get the services to write to `stdout`/`stderr` as there is no other method possible in its cases as the logging is hard coded in the application to write to specific files at specific path.

### CODE REVIEW

**Comment by nigelgbanks** [comment]
Lost some time debugging failing tests on my M1 Macbook, need to upgrade Gradle when the next release is minted to get 
https://github.com/gradle/gradle/commit/9059e16903f9536d37246264902437b645ce0825 currently we cannot perform tests on M1.

**Comment by nigelgbanks** [comment]
The failing test is caused by an odd `karaf` behaviour in that when it first starts up it writes to `karaf.log` before the loggers are configured so the first few lines of output go there. The tests is looking for these lines and timing out.

**Comment by nigelgbanks** [comment]
God that was hard to debug for https://github.com/Islandora-Devops/isle-buildkit/pull/206/commits/88f7aa69f1b6fdd27ee80ec74785909cade6ba59 at least know I know how to use `jdb`. 

This is now ready for review.

**Comment by rosiel** [comment]
From tech call: is it possible to get some testing instructions?

**Comment by nigelgbanks** [comment]
Broadly speaking to test, is that it works and logs are generated to standard out.

**Comment by g7morris** [comment]
Hi @rosiel 

Great question, apologies for the late reply. 

Hopefully my response below could be copied to `isle-dc` documentation?

Happy to help as needed here.


@nigelgbanks Feel free to add anything I may have missed. 

---

#### isle-buildkit testing

When testing isle-buildkit image releases or possible changes, a tester can:

* clone down the latest `isle-dc` to their local laptop / workstation
  * `git clone https://github.com/Islandora-Devops/isle-dc.git`

* Look up the last commit hash in the PR. In this example
  * [Allow containers to run without allocating a tty.](https://github.com/Islandora-Devops/isle-buildkit/commits/issue-174)
  * `79de15828971c10894c3cdf14eec431434c457ea` is both the commit hash and the resulting Docker image tag needed for testing.

**Example**

Screenshot from 2022-04-28 15-00-42

Within the newly cloned `isle-dc` project
* Copy the `sample.env` to `.env` as you'll need to edit the TAG value for testing
  * `cp sample.env .env`
* Change **Line 65** within the new `.env` file to the test commit hash from above
  * `nano / vi .env`
  * e.g. `TAG=79de15828971c10894c3cdf14eec431434c457ea`

* Follow the instructions from the isle-dc [Getting Started](https://github.com/Islandora-Devops/isle-dc#getting-started) section and run the following
  * `make demo`

* QC the resulting site at https://islandora.traefik.me
  * Ensure that there aren't new errors in the Status page
  * If additional testing parameters are called out in the ticket, review and test.

* If everything passes or doesn't, update the PR / issue with the following style of response.

```bash
#### Test Environment

* OS: Ubuntu 20.04 LTS Desktop
* CPU: Intel i7-10510U (8 cores) @ 4.900 GHZ
* RAM: 32 GB

---

#### Steps taken to test

 * `git clone git@github.com:Islandora-Devops/isle-dc.git`  to local laptop
 * `cd isle-dc`
 * `cp sample.env .env`
 * `vi / nano .env`
    * Changed `TAG=` to `TAG=79de15828971c10894c3cdf14eec431434c457ea`
 * `make demo`
---

#### Results

Status = Working
@nigelgbanks @g7morris Process worked great. No errors to report.
```

**Comment by g7morris** [comment]
Tested and this passes as noted here https://github.com/Islandora-Devops/isle-buildkit/issues/174

@nigelgbanks Ship it.

**Pull request merged**
