### PR TITLE
Handle.net persistent identifiers service

### PR DESCRIPTION
**Pull request by Tristaan**
This commit adds the handle.net server as a service to isle-buildkit. This can be practical for more people.

### CODE REVIEW

**Comment by nigelgbanks** [comment]
Very cool, I'll test it out either today / tomorrow.

**Comment by elizoller** [comment]
i'm intrigued by this PR - we've deployed a handle server separately from our islandora stack but communicate with it via persistent identifiers module  - is that what you're intending here - except to deploy the handle server with the whole islandora stack?

**Comment by Tristaan** [comment]
Yep this sums it up. This solution makes it more easier to maintain and you
don't have to manage other repos.

**Comment by nigelgbanks** [comment]
@Tristaan I've sent a pull request to your branch with some changes https://github.com/Tristaan/isle-buildkit/pull/1 if you are happy with that and merge it, then I'll be happy to merge your pull request here. Cheers!

**Comment by dannylamb** [comment]
_Puts on his Islandora Foundation representative hat_

Hey @Tristaan, any chance I can get you to sign a [contributor license agreement](https://islandora.ca/content/islandora-contributor-licence-agreements) for this awesome contribution? It's extremely permissive and protects both your rights to your contributions and the Islandora Foundation's ability to use your contributions.

**Comment by Tristaan** [comment]
@dannylamb ok. Contact me on my mail.
@nigelgbanks The pull request is prepared for merge

**Comment by nigelgbanks** [comment]
@Tristaan sorry to trouble you, but just in case it slipped your mind or was caught by some email filter. Could you sign and return the CCLA to @dannylamb then we can merge the pull request. Thanks!

**Comment by Tristaan** [comment]
The code will be moved to a company repository and then another pull
request will be made. This will take about a week. Hold your horses until
then. I am sorry.

**Comment by nigelgbanks** [comment]
@Tristaan no worries thanks for letting me know!

**Pull request closed without merging**
