### PR TITLE
Issue 168 vulnerability checks

### PR DESCRIPTION
**Pull request by nigelgbanks**
Also updates many packages and software to reduce the number of vulnerabilities though many still exist in the java portions of the stack.

- alpine to latest stable release
- imagemagick
- tomcat 
- fits

Requires https://github.com/Islandora-Devops/isle-gradle-docker-plugin/pull/12 to be reviewed and merged.

### CODE REVIEW

**Comment by nigelgbanks** [comment]
Tested with `isle-dc` and cantalope doesn't seem to work, on further investigation though it seems that it's looking for the files in the wrong place (i.e. in Fedora when the service file is on disc, doesn't actually seem like cantalope it self broke),

**Comment by nigelgbanks** [comment]
https://github.com/Islandora-Devops/isle-dc/pull/219 resolved the cantaloupe issue

**Comment by nigelgbanks** [comment]
Since you've been looking a pull requests, bump @dannylamb.

**Comment by g7morris** [comment]
Reporting results from testing process:

#### Test Environment

* OS: Ubuntu 20.04 LTS Desktop
* CPU: Intel i7-10510U (8 cores) @ 4.900 GHZ
* Mem: 32 GB

---

#### Test process / steps

* `git clone git@github.com:Islandora-Devops/isle-buildkit.git` to local laptop
* `git checkout `issue-168-vulnerability-checks`
* `./gradlew build`

---

#### Attempt 1

Ran for about ~15 mins with full CPU lockup the entire time. @nigelgbanks Any way we can reduce that?

```bash
#44 [stage-4 16/17] RUN ln -s /usr/local/share/.config/yarn/global/node_modules/.bin/code-server /usr/local/bin/code-server &&     ln -s /usr/local/share/.config/yarn/global/node_modules/.bin/node-gyp /usr/local/bin/node-gyp &&     ln -s /usr/local/share/.config/yarn/global/node_modules/.bin/grunt /usr/local/bin/grunt &&     ln -s /usr/local/share/.config/yarn/global/node_modules/.bin/bower /usr/local/bin/bower
#44 DONE 0.3s

#45 [stage-4 17/17] RUN chmod a=r,u+w /etc/sudo.conf
#45 DONE 0.3s

#46 exporting to image
#46 exporting layers
#46 exporting layers 3.1s done
#46 writing image sha256:164bfced1d11cf2b05c914dfac688138cbd19d4acf2bbf7ebc5c60f8456d303a done
#46 naming to docker.io/local/code-server:latest done
#46 DONE 3.1s

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':alpaca:build'.
> Process 'command 'docker'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 20s
28 actionable tasks: 28 executed

```

#### Attempt 2

* `./gradlew build`

```bash
#18 exporting to image
#18 exporting layers
#18 exporting layers 0.4s done
#18 writing image sha256:f92db08a102678c7525c8db5d0222553053d350b955af8673e0f96e87592d7de done
#18 naming to docker.io/local/alpaca:latest done
#18 DONE 0.4s

BUILD SUCCESSFUL in 2m 17s
33 actionable tasks: 7 executed, 26 up-to-date

```

@nigelgbanks 2nd time is the charm? What additional steps should I take from here? Attempt to use `isle-dc` with these created images?

**Comment by nigelgbanks** [comment]
@g7morris looks like I need to rebase this due to conflicts on main from just merging the fixes for `code-server` https://github.com/Islandora-Devops/isle-buildkit/pull/198

**Comment by g7morris** [comment]
@nigelgbanks To be clear this is something you're intending to do this week and then I can get back to testing correct?

**Comment by nigelgbanks** [comment]
@g7morris I was just sorting out the conflict and doing a quick build to check locally.

**Comment by nigelgbanks** [comment]
You should be good to test when this finishes: https://github.com/Islandora-Devops/isle-buildkit/runs/5665429249?check_suite_focus=true with the commit `562ca9854343031da934dbaaea9728bca0f9371a`

**Comment by g7morris** [comment]
Ignore previous comment. I'm too quick to test the build / push needs to finish.

**Comment by nigelgbanks** [comment]
@g7morris Unfortunately this one needs to do a full rebuild which includes compiling imagemagick under emulation for linux/arm64 which is super slow

**Comment by nigelgbanks** [comment]
@g7morris  actually in this case it might be faster to build it locally as you'd only be building for your platform.

**Comment by g7morris** [comment]
@nigelgbanks What steps would be needed to do this? I can run it over night when I get back home on my laptop (non-Arm) or Apple M1 (ARM ish)

**Comment by nigelgbanks** [comment]
@g7morris looks like it's finished :relieved: so you can just pull `562ca9854343031da934dbaaea9728bca0f9371a`. 

That being said, if you do `./gradlew build` on a Mac M1 it will build natively for `Linux/arm64` if you use the same command on older x86 Mac it will build natively for `Linux/x86_64` so it's handled automatically for you. The build and push task for the Github actions though always builds both platforms `Linux/x86_64` which is relatively fast to build, and `Linux/arm64` is built via emulation with `qemu` which is super slow. This is cause we push to Docker hub and need to support people downloading for either platform.

**Comment by nigelgbanks** [comment]
Typically we make user of heavy caching which cuts the time down from over an hour to like 10 mins or so, but this pull request changes all the base images so no caching can be used.

**Comment by nigelgbanks** [comment]
As for tests just the normal bring up the demo and muck about, the grype reports can be downloaded here:

https://github.com/Islandora-Devops/isle-buildkit/suites/5774283956/artifacts/192302600

So that bit works, it's more so just to confirm I'm not broke anything, the automated tests wouldn't pick up on.

**Comment by g7morris** [comment]
Okay I think this passes and using the arm images to test is much faster on a Mac both in the isle-dc `make demo` process (built in < 2 mins) and the gradle build.

Reporting results from testing process:

### isle-buildkit

#### Test Environment

* OS: MacOS Monterey 12.3 - (Mac Mini 9,1)
* CPU: 8 cores
* Mem: 16 GB

---

#### Test process / steps

* `git clone git@github.com:Islandora-Devops/isle-buildkit.git` to local laptop
* `git checkout `issue-168-vulnerability-checks`
* `./gradlew build`

---

#### Attempt 1

Ran for about < 6 mins with not so full CPU lockup the entire time. Close but it did go heavy into swap ~ 8GB.

```bash
BUILD SUCCESSFUL in 5m 32s
33 actionable tasks: 33 executed
```

---

### isle-dc 

#### Test Environment

* OS: MacOS Monterey 12.3 - (Mac Mini 9,1)
* CPU: 8 cores
* Mem: 16 GB

---

#### Steps taken to test

 * `git clone git@github.com:Islandora-Devops/isle-dc.git`  to local laptop
 * `cd isle-dc`
 * `cp sample.env .env`
 * `vi / nano .env`
    * Changed `TAG=` to `TAG= 562ca9854343031da934dbaaea9728bca0f9371a`
 * `make demo`
---

#### Results

@nigelgbanks Process worked great and much faster than x86. No new errors. Site is snappier and drush commands don't lag. Nice

Think we can ship this one eh?

**Comment by nigelgbanks** [comment]
@g7morris awesome I'll merge it then :+1:

**Pull request merged**
