### PR TITLE
Matomo upgrade to 5.x

### PR DESCRIPTION
**Pull request by g7morris**

### CODE REVIEW

**Comment by nigelgbanks** [comment]
Screenshot 2024-01-28 at 18 48 40

Initial local test ran into this, I'll have a look a bit later when I get more time to see what's up with that.

**Comment by nigelgbanks** [comment]
@g7morris the issue I had was with a clean installation. I've pushed a fix and raised a pull request against your organization's repository.  https://github.com/Born-Digital-US/isle-buildkit/pull/4

No worries about this pull request, but if you could in the future create branches in this repo, that would be ideal. As then the CI system with automated tests will run, and be visible in the pull request.

Cheers

**Comment by g7morris** [comment]
Perhaps we should make a section in the README.md to this effect e.g. Contributing etc that details the way committers and contributors should approach this?

My apologies for the confusion, I'm just reviewing other previous PRs and am not totally clear on how any of us are following the house rules. Sorry to track mud on the carpet, I promise I can learn and behave. ;)

**Comment by g7morris** [comment]
So other than this fix that I've now merged, is this ready to be merged?

**Comment by nigelgbanks** [comment]
> Just to clarify this process should now be the following?

Oh I wouldn't worry about creating a fork and doing work there. You can just create a branch on this repo and do your work here. At least then it will be visible and prevent others from working on the same thing. Also the pull requests, etc. will be on the CI system and so it will validate changes.

Though you can do as you please, there is no hard requirement here. I just think it would be easier and more open not to do work in isolation.

**Pull request merged**
