### PR TITLE
Handle.net persistent identifiers service

### PR DESCRIPTION
**Pull request by Tristaan**
As discussed in [Pull request #104](https://github.com/Islandora-Devops/isle-buildkit/pull/104). This pull request adds handle.net service to isle-buildkit.

I resolved the merge conflicts because of new commits in isle-buildkit so this branch is ready for merge.

--
tristan.sneider@abak.net

### CODE REVIEW

**Comment by nigelgbanks** [comment]
Cheers @Tristaan I'll do some testing today!

**Comment by dannylamb** [comment]
abak.net has been gracious enough to sign a cCLA, so feel free to merge after testing @nigelgbanks 

Thanks for this @Tristaan !

**Comment by nigelgbanks** [comment]
This looks good to me, I tested locally only a few changes were required due to how https://github.com/Islandora-Devops/isle-buildkit/pull/96 changed the Confd/Environment variable behavoir.

Once this is merged: https://github.com/Abak-net-d-o-o/isle-buildkit/pull/1, I can merge it here and we;ll all be done!

**Review by nigelgbanks — APPROVED** [review]

**Comment by nigelgbanks** [comment]
Thanks again @Tristaan!

**Pull request merged**
