### PR TITLE
Testing processing just the first page of pdfs for thumbnails and ser…

### PR DESCRIPTION
**Pull request by dannylamb**
…vice files

Can't seem to build this locally.  Hoping that Github actions can help me :pray:

### CODE REVIEW

**Comment by nigelgbanks** [comment]
@dannylamb should this be closed?

**Comment by dannylamb** [comment]
It's part of a fix I haven't gotten the time to advocate for in the
community.  TL;DR it cuts pdf thumbnail processing times in half, easily,
if not more.  Leave it here for a bit and I'll see if I can get the rest
through on the application end of things.

**Comment by g7morris** [comment]
@dannylamb Is this something you plan on picking up this month or next? Would love to put this in a release. Thanks!

**Comment by g7morris** [comment]
@dannylamb Would you like us to consider this for this month's release? Could you respond on this and I can then make it an issue for us to test etc.

**Comment by dannylamb** [comment]
Eh, hang on.  Let me see if the PR for crayfish that this references got merged.

**Comment by dannylamb** [comment]
:face_with_head_bandage: Gotta go make an issue for this.  It's a small fix that'd be useful for everybody and it's just been languishing as a branch.

**Comment by dannylamb** [comment]
When https://github.com/Islandora/Crayfish/pull/163 gets merged, we can delete this branch/pr because we'll get this when we get the latest crayfish.

**Comment by dannylamb** [comment]
It was merged.  I'll keep this branch since I'm using this container in a few places.  But once you slice another version of ISLE, this PR and branch can go away.

**Comment by g7morris** [comment]
@nigelgbanks & @dannylamb Is this ready to go?

**Comment by dannylamb** [comment]
We would need to update the commit hash for crayfish to `48cd6acfe4b6892d4ffa20e4fdfe16057a19a142` to get the latest 2.x code.  After that this can be closed.

**Comment by dannylamb** [comment]
...and done.

**Comment by nigelgbanks** [comment]
The build failure seems to be a network timeout, I'm running it again now to check. In the meanwhile I'll give a quick test locally.

**Comment by nigelgbanks** [comment]
Hmm, looks like something has changed under our feet with ImageMagick I'll investigate further.

**Comment by nigelgbanks** [comment]
The issue was fixed on `main` so I just rebased this work on `main`.

**Comment by nigelgbanks** [comment]
Old:
```
[2022-10-19 13:58:15] request.INFO: Matched route "convert_get". {"route":"convert_get","route_parameters":{"_route":"convert_get","_controller":"App\\Islandora\\Houdini\\Controller\\HoudiniController::convert"},"request_uri":"http://houdini:8000/convert","method":"GET"} []
[2022-10-19 13:58:15] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"admin\", authenticated=true, roles=\"authenticated, fedoraadmin\"))","authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2022-10-19 13:58:15] app.INFO: Convert request. [] []
[2022-10-19 13:58:15] app.INFO: Imagemagick Command: {"cmd":"convert - -thumbnail 100x100 jpeg:-"} []
```


New:
```
[2022-10-19 13:51:27] php.INFO: User Deprecated: The "Symfony\Component\Debug\DebugClassLoader" class is deprecated since Symfony 4.4, use "Symfony\Component\ErrorHandler\DebugClassLoader" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Symfony\\Component\\Debug\\DebugClassLoader\" class is deprecated since Symfony 4.4, use \"Symfony\\Component\\ErrorHandler\\DebugClassLoader\" instead. at /var/www/crayfish/Houdini/vendor/symfony/debug/DebugClassLoader.php:16)"} []
[2022-10-19 13:51:27] request.INFO: Matched route "convert_get". {"route":"convert_get","route_parameters":{"_route":"convert_get","_controller":"App\\Islandora\\Houdini\\Controller\\HoudiniController::convert"},"request_uri":"http://houdini:8000/convert","method":"GET"} []
[2022-10-19 13:51:27] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"admin\", authenticated=true, roles=\"authenticated, fedoraadmin\"))","authenticator":"Islandora\\Crayfish\\Commons\\Syn\\JwtAuthenticator"} []
[2022-10-19 13:51:27] app.INFO: Convert request. [] []
[2022-10-19 13:51:27] app.INFO: Imagemagick Command: {"cmd":"convert pdf:-[0] -thumbnail 100x100 png:-"} []
172.28.0.11 - - [19/Oct/2022:13:51:27 +0000] "GET /convert HTTP/1.1" 200 7738 "-" "Apache-HttpClient/4.5.3 (Java/1.8.0_345)" "-"
```

Can confirm it's working locally.

**Review by nigelgbanks — APPROVED** [review]

**Comment by dannylamb** [comment]
:bow: Thanks @nigelgbanks

**Pull request merged**
